In [69]:
# 문제 1
import pandas as pd

df = pd.read_csv("drinks.csv")
# print(df)
# print(df.head())
# df.info()
# df['continent'].value_counts()

# 대륙별 맥주 소비량의 평균
mean_val = df.groupby("continent")['beer_servings'].mean()
# print(mean_val)

# 평균이 가장 큰 대륙
continent_top = mean_val.idxmax()
print(continent_top)

# 평균이 가장 큰 대륙 중 맥주 소비량이 5번째 많은 국가
result = (df['continent'] == continent_top)
# df = df[result]
# print(df)
df_new = df[result].sort_values('beer_servings', ascending=False)
print(df_new)
print(df_new.iloc[4, 1])
print(df_new.iloc[4][['beer_servings', 'country']])

Europe
                country  beer_servings  spirit_servings  wine_servings  \
45       Czech Republic            361              170            134
65              Germany            346              117            175
135              Poland            343              215             56
98            Lithuania            343              244             56
81              Ireland            313              118            165
140             Romania            297              122            167
16              Belgium            295               84            212
160               Spain            284              157            112
151              Serbia            283              131            127
93               Latvia            281              216             62
9               Austria            279               75            191
156            Slovenia            270               51            276
60              Finland            263              133             97
120         Netherlands            251               88            190
3               Andorra            245              138            312
99           Luxembourg            236              133            271
75              Hungary            234              215            185
76              Iceland            233               61             78
25             Bulgaria            231              252             94
42              Croatia            230               87            254
48              Denmark            224               81            278
57              Estonia            224              194             59
182      United Kingdom            219              126            195
180             Ukraine            206              237             45
155            Slovakia            196              293            116
136            Portugal            194               67            339
44               Cyprus            192              154            113
166         Switzerland            185              100            280
126              Norway            169               71            129
165              Sweden            152               60            186
105               Malta            149              100            120
15              Belarus            142              373             42
67               Greece            133              112            218
61               France            127              151            370
139             Moldova            109              226             18
170           Macedonia            106               27             86
1               Albania             89              132             54
83                Italy             85               42            237
21   Bosnia-Herzegovina             76              173              8
64              Georgia             52              100            149
113          Montenegro             31              114            128
10           Azerbaijan             21               46              5
7               Armenia             21              179             11
147          San Marino              0                0              0
111              Monaco              0                0              0

     total_litres_of_pure_alcohol continent
45                           11.8    Europe
65                           11.3    Europe
135                          10.9    Europe
98                           12.9    Europe
81                           11.4    Europe
140                          10.4    Europe
16                           10.5    Europe
160                          10.0    Europe
151                           9.6    Europe
93                           10.5    Europe
9                             9.7    Europe
156                          10.6    Europe
60                           10.0    Europe
120                           9.4    Europe
3                            12.4    Europe
99                           11.4    Europe
75                           11.3    Europe
76                            6.6    Europe
25                           10.3    Europe
42                           10.2    Europe
48                           10.4    Europe
57                            9.5    Europe
182                          10.4    Europe
180                           8.9    Europe
155                          11.4    Europe
136                          11.0    Europe
44                            8.2    Europe
166                          10.2    Europe
126                           6.7    Europe
165                           7.2    Europe
105                           6.6    Europe
15                           14.4    Europe
67                            8.3    Europe
61                           11.8    Europe
139                           6.3    Europe
170                           3.9    Europe
1                             4.9    Europe
83                            6.5    Europe
21                            4.6    Europe
64                            5.4    Europe
113                           4.9    Europe
10                            1.3    Europe
7                             3.8    Europe
147                           0.0    Europe
111                           0.0    Europe
313
beer_servings        313
country          Ireland
Name: 81, dtype: object

In [15]:
import pandas as pd

df = pd.read_csv("drinks.csv", usecols=["beer_servings", "wine_servings", "total_litres_of_pure_alcohol", "continent"])
df.head()

df.groupby("continent")['beer_servings'].mean()

continent
Africa            61.471698
Asia              37.045455
Europe           193.777778
North America    145.434783
Oceania           89.687500
South America    175.083333
Name: beer_servings, dtype: float64

In [87]:
# 문제2
import pandas as pd

df = pd.read_csv("tourist.csv")
df

df['방문객 합계'] = df['관광'] + df['공무'] + df['사업'] + df['기타']
df['관광객비율'] = df['관광'] / df['방문객 합계']
# print(df)

# 방법1
# 관광객 비율이 두 번째로 높은 국가
# print(df.sort_values('관광객비율', ascending=False))
# a = df.sort_values('관광객비율', ascending=False).iloc[1, 3]
# print(a)
# print(df.sort_values('관광', ascending=False))
# b = df.sort_values('관광', ascending=False).iloc[1, 2]
# print(b)
# print(a + b)

# 방법2
# a = df.nlargest(2, '관광객비율').iloc[1, 3]
a = df.nlargest(2, '관광객비율').iloc[1]['사업']
print(a)
b = df.nlargest(2, '관광').iloc[1, 2]
print(b)
print(a + b)

203
238
441

In [93]:
# 문제3
import pandas as pd

df = pd.read_csv("chem.csv")
print(df)
print(df.info())

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df['co'] = scaler.fit_transform(df[['co']])
df['nmhc'] = scaler.fit_transform(df[['nmhc']])

print(df)

# 표준편차
co_std = df['co'].std()
print(co_std)
nmhc_std = df['nmhc'].std()
print(nmhc_std)

result = round((co_std - nmhc_std), 3)
print(result)

   sample   co  nmhc  etc
0     샘플1   79    54   31
1     샘플2   84    57   58
2     샘플3  109    74  113
3     샘플4   15    77   21
4     샘플5   65    77  115
..    ...  ...   ...  ...
95   샘플96   56    58   86
96   샘플97   33    59  111
97   샘플98   55    79  105
98   샘플99   69    51   59
99  샘플100   94    45   59

[100 rows x 4 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   sample  100 non-null    object
 1   co      100 non-null    int64
 2   nmhc    100 non-null    int64
 3   etc     100 non-null    int64
dtypes: int64(3), object(1)
memory usage: 3.3+ KB
None
   sample        co      nmhc  etc
0     샘플1  0.680851  0.500000   31
1     샘플2  0.734043  0.534091   58
2     샘플3  1.000000  0.727273  113
3     샘플4  0.000000  0.761364   21
4     샘플5  0.531915  0.761364  115
..    ...       ...       ...  ...
95   샘플96  0.436170  0.545455   86
96   샘플97  0.191489  0.556818  111
97   샘플98  0.425532  0.784091  105
98   샘플99  0.574468  0.465909   59
99  샘플100  0.840426  0.397727   59

[100 rows x 4 columns]
0.2856516497116944
0.3030617020578397
-0.017

#### 제2유형

In [123]:
import pandas as pd

train = pd.read_csv("churn_train.csv")
test = pd.read_csv("churn_test.csv")

# print(train.head())
# train.info()
print(train.describe())

# 레이블 인코딩
from sklearn.preprocessing import LabelEncoder

# cols = train.columns
cols = train.select_dtypes(include='O').columns
print(cols)

encoder = LabelEncoder()
for col in cols:
    train[col] = encoder.fit_transform(train[col])
    test[col] = encoder.fit_transform(test[col])

train.info()
test.info()
print(train.head())

# 변수 선택
X = train.drop(columns=["TotalCharges"])
y = train["TotalCharges"]

train.info()

# 학습용(훈련/검증) 데이터 분할
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X,
                                                   y,
                                                   test_size=0.2,
                                                   random_state=30)

print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

# 모델 학습 및 평가 - 회귀, 평균 제곱 오차
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

model = RandomForestRegressor(random_state=0)
model.fit(X_train, y_train)
pred = model.predict(X_test)
print(pred)

mae = mean_absolute_error(y_test, pred)
print("MAE:", mae)

# 평가용 데이터 - 예측 및 파일 제출
pred2 = model.predict(test)
pred2

result = pd.DataFrame({'pred': pred2})
result.to_csv("result.csv", index=False)

pd.read_csv("result.csv")

       SeniorCitizen       tenure  TotalCharges
count    4116.000000  4116.000000   4116.000000
mean        0.506560    36.551263   2566.580782
std         0.500018    20.939386   1911.356766
min         0.000000     1.000000     20.030000
25%         0.000000    18.000000   1020.922500
50%         1.000000    37.000000   2144.285000
75%         1.000000    55.000000   3765.670000
max         1.000000    72.000000   8589.600000
Index(['customerID', 'gender', 'Partner', 'Dependents', 'PhoneService',
       'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup',
       'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies',
       'Contract', 'PaperlessBilling', 'PaymentMethod'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4116 entries, 0 to 4115
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        4116 non-null   int32
 1   gender            4116 non-null   int32
 2   SeniorCitizen     4116 non-null   int64
 3   Partner           4116 non-null   int32
 4   Dependents        4116 non-null   int32
 5   tenure            4116 non-null   int64
 6   PhoneService      4116 non-null   int32
 7   MultipleLines     4116 non-null   int32
 8   InternetService   4116 non-null   int32
 9   OnlineSecurity    4116 non-null   int32
 10  OnlineBackup      4116 non-null   int32
 11  DeviceProtection  4116 non-null   int32
 12  TechSupport       4116 non-null   int32
 13  StreamingTV       4116 non-null   int32
 14  StreamingMovies   4116 non-null   int32
 15  Contract          4116 non-null   int32
 16  PaperlessBilling  4116 non-null   int32
 17  PaymentMethod     4116 non-null   int32
 18  TotalCharges      4116 non-null   float64
dtypes: float64(1), int32(16), int64(2)
memory usage: 353.8 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1764 entries, 0 to 1763
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        1764 non-null   int32
 1   gender            1764 non-null   int32
 2   SeniorCitizen     1764 non-null   int64
 3   Partner           1764 non-null   int32
 4   Dependents        1764 non-null   int32
 5   tenure            1764 non-null   int64
 6   PhoneService      1764 non-null   int32
 7   MultipleLines     1764 non-null   int32
 8   InternetService   1764 non-null   int32
 9   OnlineSecurity    1764 non-null   int32
 10  OnlineBackup      1764 non-null   int32
 11  DeviceProtection  1764 non-null   int32
 12  TechSupport       1764 non-null   int32
 13  StreamingTV       1764 non-null   int32
 14  StreamingMovies   1764 non-null   int32
 15  Contract          1764 non-null   int32
 16  PaperlessBilling  1764 non-null   int32
 17  PaymentMethod     1764 non-null   int32
dtypes: int32(16), int64(2)
memory usage: 137.9 KB
   customerID  gender  SeniorCitizen  Partner  Dependents  tenure  \
0         308       1              0        0           0       7
1         797       0              1        0           1      53
2         793       0              1        0           1      68
3        1852       1              1        0           1      44
4        1839       1              0        1           0       7

   PhoneService  MultipleLines  InternetService  OnlineSecurity  OnlineBackup  \
0             1              2                2               1             1
1             0              1                1               2             2
2             0              1                0               2             2
3             0              1                2               1             1
4             1              2                1               0             2

   DeviceProtection  TechSupport  StreamingTV  StreamingMovies  Contract  \
0                 1            1            1                1         2
1                 0            2            2                2         0
2                 2            0            0                2         0
3                 1            1            1                1         0
4                 2            0            2                0         1

   PaperlessBilling  PaymentMethod  TotalCharges
0                 0              2        163.45
1                 0              1       4140.89
2                 0              3       5152.36
3                 1              1       5251.84
4                 0              2        725.69
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4116 entries, 0 to 4115
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        4116 non-null   int32
 1   gender            4116 non-null   int32
 2   SeniorCitizen     4116 non-null   int64
 3   Partner           4116 non-null   int32
 4   Dependents        4116 non-null   int32
 5   tenure            4116 non-null   int64
 6   PhoneService      4116 non-null   int32
 7   MultipleLines     4116 non-null   int32
 8   InternetService   4116 non-null   int32
 9   OnlineSecurity    4116 non-null   int32
 10  OnlineBackup      4116 non-null   int32
 11  DeviceProtection  4116 non-null   int32
 12  TechSupport       4116 non-null   int32
 13  StreamingTV       4116 non-null   int32
 14  StreamingMovies   4116 non-null   int32
 15  Contract          4116 non-null   int32
 16  PaperlessBilling  4116 non-null   int32
 17  PaymentMethod     4116 non-null   int32
 18  TotalCharges      4116 non-null   float64
dtypes: float64(1), int32(16), int64(2)
memory usage: 353.8 KB
(3292, 18) (824, 18) (3292,) (824,)
[4135.8255 3007.1728 3908.818  2921.6159 2610.3577  876.803  4039.4538
 3121.8706 3583.8735 3914.5741 3169.358  3662.2578 3577.3725 1010.4798
 1413.6996  469.7475  248.0451 1668.4705 3020.4762 4264.7134 1942.539
 4575.6909 5001.5324 3438.4306 1077.8284 3536.7293 2700.2708 4631.4148
 1121.9109 2073.3741  148.0759 3933.2993 1984.1015 2412.473  4058.2678
 2393.7409 3227.0215 2948.7883 1574.6931 2933.6158  738.6897 3820.8218
 2233.8874 5855.0883  567.099  1882.4063 1724.8789  412.9718 3819.0474
 6050.8705  931.4194  949.0232 3821.5237 3392.0595 5173.2519  798.7862
  982.5922 2768.6933 2230.6669 2355.6656 2840.272   558.1764 3441.6231
 3539.2744 4637.99   2741.6355  764.4709 4915.5607 1725.8539 3609.2112
 3081.7739 5192.0712  892.2492  498.7686 3123.6053 4706.5035 1077.5901
 3132.9705 3931.3921 1040.6702 4198.5686 2034.7905 1012.3151 2371.578
 6656.7813 2364.9763 2770.1485  876.6011 4906.3184  276.605  1884.4121
 3914.5795 4060.3565 2190.0739 4057.15   2566.5423 2205.5054 2889.1941
 1944.7582  859.3599 3736.9236 4050.0387 3338.2656 4315.3812  622.0209
  742.8337  891.5332   78.9186 2085.8648 1570.4565  963.5989 3861.5119
  560.1566 1440.6906  376.1004 4147.9481 2670.6105 1089.3062 1505.2439
 2890.6117  204.7919 3806.0162 2690.361  3334.0587  651.8321 2127.928
  302.1043 1432.4791 1018.1717 4624.944  5419.3102 6729.9231  730.5723
 3864.3456 2031.8636  847.8108 1895.9196  133.0938 1333.4056 1066.836
 2976.721  2267.2572 2814.3136 3982.1673 1633.8256 5173.1353  956.7975
 3152.8418 1752.0997 6009.5911 3957.7608 3684.4743 3165.3541 4392.8254
 2427.3443 3687.4414 3278.0269  787.8328  300.376  2648.4068 1151.3877
 4335.0798 1925.1122 5678.4295 1378.6354 1961.4166  276.5012 3136.7042
 3334.8945 2724.0437 1060.689   555.2631 1116.3888  623.0716  221.7968
 2580.4424 1177.6724 4496.6641 4443.1357   70.4195 1132.0146 5404.8345
 1820.5564 1064.4151  866.5176 4917.7242 2449.3683 1230.415   205.1867
 1443.2761  192.4659  999.5718 1994.7021 3513.4127 3712.2306 3541.7627
 4310.0245  315.5285 3621.4165 3879.9306  845.9213  209.9443 5168.8127
  980.3499 4107.4733 1081.9778 1942.0416 3865.4793 2702.6154  650.6268
  766.3568 3749.9482  754.9934 1351.0175 3642.1326 3988.2486 5160.6751
 4824.7153 3442.114  1567.5586 1423.9959 1620.2589  292.362   243.344
 3212.3445 3179.8746 1068.7211 3954.5596 1615.6169 4200.5455 1583.5419
 4733.5017 3381.379  2048.5662 1723.2869  888.1537 1796.34   1023.2227
 1414.5437 2159.7974 4538.2864  686.551  3199.527  1437.9655 4924.6981
 1894.7942  995.5912  391.0829 2770.9636   58.727  3022.811  1062.6486
 1915.0524 1876.4368 4554.4995 5355.6063 4941.8314 1147.1462 5830.1634
  796.478  1779.8732 3512.6311 3942.9542 3711.8456  895.1725 4109.9646
 2441.142   650.5156 2008.2339 1367.5917 2009.1877  150.1646 2555.7929
 1814.9999 1788.6014 1163.5194 1952.3059 4465.7214  409.2251 2580.9913
 1701.6923  624.0933 3342.7021  987.1345 4624.3767 4884.214  5924.2493
 1818.799  5113.4217 1660.7255  359.4228 3902.0896 3918.1742 1313.3733
 4869.5149 1725.7765  693.9356  768.4238 2297.3976 3872.1213  410.6231
  942.9465  971.6281 4066.4917 3820.67   3344.3726  937.615  3348.4459
 1091.6196 1587.4268 1992.9408  331.2081 2489.4828 1334.5114  602.6019
 3272.0907 2260.0259  522.1429 3494.814  3823.5235 2571.7444 4018.3042
 3655.2582 4216.1871 1323.1326 1922.084  3055.9042 2763.3768 2742.9808
  370.1394 3603.0039 1808.8833 5194.021  2259.7969 1048.9458 5339.4217
 1079.5206 1619.426  4582.8637 3652.2683  954.2266 2155.7928 1965.9621
 2054.6091  328.3585  318.8597 4842.1505 3134.3205   59.7192 5749.6393
  627.8675   78.5203 2311.9266 2657.5128 4669.6957 1322.0876  784.6213
 4404.0321 2203.8021 2583.4448  336.6755 2181.3367  255.2528   98.4107
 1446.3878 2591.467   367.4572  791.7925 5007.9707 3934.9657 4950.4527
 2187.84   1562.2535 2244.6615 2287.9378  381.8582  425.518  2606.1369
 3762.8737  372.852   484.528  3921.0749  823.5321  944.5494  311.0765
 1800.1607 2171.0699  343.2631 3361.2677  280.2304 2179.6349 4357.6739
 1893.0137 2493.6685 3780.2899  675.5756  784.8547 4437.7447 4588.5905
   49.1269 4030.8944 3025.8208 2513.8592  642.8159  476.681  1141.6361
  284.5656 4018.3709 3432.0626 5469.6697  781.7104 5671.3634 3409.422
  502.0302 2891.0025 3557.7649 4098.8352 3499.4735 4774.029  1847.9917
 3378.5256 4149.3935  120.47   3010.8021 4613.6525 3542.2507 3270.7786
   69.7328  692.8742  783.1901 2960.2334  430.8586  675.6335 3004.2265
 4461.9075 3480.8786  160.4752 1443.1168 3750.6924 3844.4192 3820.2039
  946.6854 3856.0138 2654.5781 2547.1964 1301.8455 6039.1293 1775.3309
 1421.9638 3832.1465 5657.2482 3579.676  1204.1143 4368.3303 2935.7735
  779.9316 3089.9882 1219.8645 1148.7353 4138.1394 5812.4302 4284.0934
 4412.3104  926.5946 3554.5157 2639.3492  120.0884 2561.1399 3232.0752
 2879.1378  417.5704 3689.8023 3220.4607 3023.4748 1275.1888 3564.7982
 4573.5454 4159.868  5236.2799 1416.8598 3673.0493 5419.6071  832.2841
 1637.838  2028.802   919.898  1929.2129 4398.9055 2858.7226 2743.6338
 3808.1058  457.5348 2685.8326 2858.7918  217.8229 4008.6334 1162.2911
 3906.8534 4030.8424 3940.2236 3543.1298 2409.9554 3573.2769 5279.1511
 6081.4529 3268.8799 1391.078  3610.0556 3894.4677 2395.0472 4796.9656
  104.8403  999.6244 1982.5857 1563.7474 3018.6939 3357.6472 1124.3977
 3044.1695 1410.0005 2031.9433 3770.1613 2977.7974 3073.7191  407.8371
 1868.9766 4398.3299 2527.0747 5003.2258 2980.6464  401.4222 3011.6869
 2224.6746 3908.9704 4972.5926 3843.5973  599.2467 2831.4569 4697.8344
 2585.1456  445.7084 5144.6826 1065.2982 3083.0978 1225.9935 3693.4121
  818.9874 3251.2719 1517.409  2673.3975 3826.7398  860.6694 4529.1987
  538.313  1087.486  1481.9587 4407.3912 3067.3603  952.5334 1697.8599
   65.8965  692.7778 2194.1024  810.3069 4620.4931 2487.1961 3366.6007
  944.1772  752.6325 4178.6026 2580.0478 1163.1186 1870.4848 1803.6062
 1794.2921 3238.3498 2352.5559 4555.1557 3119.3947 3534.8983 1243.9151
 5093.3147  591.3539 2234.2476 1041.8042 3012.9893 2923.9261  385.9128
 2767.499  4632.0612 1240.9654 4556.3296 3137.8998 2107.839   974.9095
 1711.9095 1483.0963 1678.9092   61.8638 4699.6305 3853.6486 1888.3247
   92.4722 5763.6929 1213.0601 3420.9515 4135.1469 4561.4367 1920.0455
 5421.741   765.0048 2628.5895 2296.8756 4743.8808 2156.313  2439.1089
 3254.6127  935.0174 3627.8648 2853.2431 2856.4767 2005.8351 3526.4916
 1311.8283 3416.3674 4980.4297 1803.2039 3307.3176 1417.5378 3680.3712
 1914.4129 4775.4267 3701.0267 3608.9191  479.2601 3537.3042 1775.9199
  267.6156  920.1041 3990.0699 4936.081  2419.7593 4892.4372 4223.9191
 4008.7264 3429.3044 3013.4322 2831.6237  412.8458 4033.6658  830.8012
  889.7084  917.5221   57.5936 2898.3856 2453.5205 2526.6697 2333.7975
 1218.5286 2056.4025  845.3131 2309.9369 2894.6819 3240.2765 3209.0826
 4963.2901 5194.3595 2051.8196 1254.8225 1059.985   600.6427 1194.7424
 1165.9788 4479.6235 2571.8952 3894.7437 3182.534   862.7349 2763.3304
 3620.5621 3171.5865 4898.3926 4674.4904 5348.5626  799.1334 2340.5371
 1774.7657 4116.1917 3305.8045 4555.1547 2012.9047 1119.6878 4604.7502
 3340.925   586.6997 3544.5138  750.3425 3947.6437  473.4576 3837.1076
 1759.194  5011.6043   69.7219  987.6492 3489.4683 2827.3557  748.364
 4254.5741  898.6008 3012.5903  801.1859  347.3072  480.3235  114.7796
 1234.1942 5376.8229 2263.8711 3853.3384 3175.9498 1095.05   1201.1536
 4052.9618 2901.6773 2196.3089 3675.7869  611.6237 1463.762  1887.7364
 3981.5388 2835.5454  205.5626  980.9053 1902.9872  443.6919 6230.0399
 2913.8293 3113.4487 3132.5943 1370.2301 4686.5082 3537.7473 3205.5645
 4868.9267 3162.1065 3669.3437  703.0863 2300.0837 1938.936  2719.9165
 2879.5802 1883.0937  741.3832 2973.1776  588.7665 2526.0234 4167.1134
 5368.8669 1773.8515  180.401  2715.5059 1364.3363 2708.3428 2217.2583
 3174.4605  554.5133 4245.6589 5009.5733 2198.2141 1498.1379 1265.0556
 1932.1675  567.0575  907.2231  684.2641 2267.7313 4681.6976 2617.5648
  588.1005 3050.4724 1554.8837 5093.2611 2438.4471 1989.0355 2587.9144
 3691.5527 2596.7235 3363.1777 4691.6478 2973.6092 2626.294   617.9408
 2527.7603 1706.1115 4385.9707  109.2744 1402.6949 3877.8128 3609.5118
  239.355   154.9706  118.9337  775.2303 5078.9531 2967.7162 2412.0279
 1035.4614 2376.6868  606.5532 2049.8502 1858.7642  381.6238 3702.1938
 4900.0093 1420.8041 1534.37   3285.7072 1847.1599 4688.7544 1011.1418
 4332.5997 3482.4825 5459.888  2626.9326 2840.0118]
MAE: 896.5075083737865

           pred
0     3566.2641
1      825.5758
2     4401.3094
3      902.8376
4     1223.1807
...         ...
1759   318.6108
1760  4501.7479
1761  3626.8308
1762  1172.2977
1763  3953.6088

[1764 rows x 1 columns]

#### 제3유형

In [143]:
# 문제1
import pandas as pd
from statsmodels.formula.api import logit
df = pd.read_csv("churn.csv")
# print(df.head())
df.info()

# 종속변수 - Churn, 독립변수 - 나머지 칼럼
formula = """
    Churn ~ AccountWeeks + ContractRenewal + DataPlan + DataUsage + CustServCalls +
    DayMins + DayCalls + MonthlyCharge + OverageFee + RoamMins
"""

model = logit(formula, data=df).fit()

# 유의하지 않은 독립변수의 개수 구하기
# print(model.summary())
# Intercept항 제외
print(model.pvalues[1:])

print(model.pvalues[1:] > 0.05)
# True의 합
print(sum(model.pvalues[1:] > 0.05))

# 문제2
# 유의한 변수 선택
print(model.pvalues < 0.05)

# 로지스틱 회귀
model2 = logit('Churn ~ DataUsage + DayMins', data=df).fit()
print(model2.summary())
# 회귀 계수의 합계
print("회귀계수:", model2.params)
print("회귀계수의 합계:",round(sum(model2.params), 3))

import numpy as np
# 'DataUsage'의 회귀 계수
coef = model2.params['DataUsage']
print(coef)

# 오즈비 계산 - 5만큼 증가
print(round(np.exp(coef*5), 3))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Churn            1000 non-null   int64
 1   AccountWeeks     1000 non-null   int64
 2   ContractRenewal  1000 non-null   int64
 3   DataPlan         1000 non-null   int64
 4   DataUsage        1000 non-null   float64
 5   CustServCalls    1000 non-null   int64
 6   DayMins          1000 non-null   float64
 7   DayCalls         1000 non-null   int64
 8   MonthlyCharge    1000 non-null   float64
 9   OverageFee       1000 non-null   float64
 10  RoamMins         1000 non-null   float64
dtypes: float64(5), int64(6)
memory usage: 86.1 KB
Optimization terminated successfully.
         Current function value: 0.393603
         Iterations 6
AccountWeeks       0.265370
ContractRenewal    0.621969
DataPlan           0.145825
DataUsage          0.019118
CustServCalls      0.063182
DayMins            0.036410
DayCalls           0.598956
MonthlyCharge      0.436350
OverageFee         0.724826
RoamMins           0.770181
dtype: float64
AccountWeeks        True
ContractRenewal     True
DataPlan            True
DataUsage          False
CustServCalls       True
DayMins            False
DayCalls            True
MonthlyCharge       True
OverageFee          True
RoamMins            True
dtype: bool
8
Intercept           True
AccountWeeks       False
ContractRenewal    False
DataPlan           False
DataUsage           True
CustServCalls      False
DayMins             True
DayCalls           False
MonthlyCharge      False
OverageFee         False
RoamMins           False
dtype: bool
Optimization terminated successfully.
         Current function value: 0.397599
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:                  Churn   No. Observations:                 1000
Model:                          Logit   Df Residuals:                      997
Method:                           MLE   Df Model:                            2
Date:                Fri, 24 Jan 2025   Pseudo R-squ.:                 0.01375
Time:                        11:44:35   Log-Likelihood:                -397.60
converged:                       True   LL-Null:                       -403.14
Covariance Type:            nonrobust   LLR p-value:                  0.003908
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -1.0395      0.303     -3.434      0.001      -1.633      -0.446
DataUsage     -0.1697      0.071     -2.376      0.017      -0.310      -0.030
DayMins       -0.0039      0.002     -2.264      0.024      -0.007      -0.001
==============================================================================
회귀계수: Intercept   -1.039494
DataUsage   -0.169734
DayMins     -0.003863
dtype: float64
회귀계수의 합계: -1.213
-0.1697343021232909
0.428

In [151]:
# 문제 2
import pandas as pd
df = pd.read_csv("piq.csv")
print(df.head())

from statsmodels.formula.api import ols
model = ols("PIQ ~ Brain + Height + Weight", data=df).fit()
print(model.summary())

# p-value가 가장 작은 변수의 회귀 계수
coef = model.params['Brain']
print("회귀 계수:", round(coef, 3))

# 결정 계수 - 모델이 종속변수의 변동을 얼마나 잘 설명하는지 나타내는 지표이다.
print("결정 계수:", round(model.rsquared, 2))

# 새로운 데이터 생성
new_df = pd.DataFrame({
    'Brain': [90],
    'Height': [70],
    'Weight': [150]
})
new_df

# PIQ 예측
pred = model.predict(new_df)
print(pred)
print(type(pred)) # 시리즈
print("PIQ:", round(pred[0])) #인덱스로 찾기

   PIQ  Brain  Height  Weight
0  132  85.78    62.5     127
1   96  86.54    68.0     135
2   84  90.49    66.3     134
3  134  79.06    62.0     122
4   86  88.91    70.0     180
                            OLS Regression Results
==============================================================================
Dep. Variable:                    PIQ   R-squared:                       0.370
Model:                            OLS   Adj. R-squared:                  0.329
Method:                 Least Squares   F-statistic:                     9.024
Date:                Fri, 24 Jan 2025   Prob (F-statistic):           8.25e-05
Time:                        11:51:42   Log-Likelihood:                -217.27
No. Observations:                  50   AIC:                             442.5
Df Residuals:                      46   BIC:                             450.2
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     74.5114     50.564      1.474      0.147     -27.269     176.292
Brain          2.3431      0.456      5.141      0.000       1.426       3.261
Height        -2.6444      1.064     -2.485      0.017      -4.786      -0.503
Weight         0.0406      0.167      0.243      0.809      -0.296       0.377
==============================================================================
Omnibus:                        8.608   Durbin-Watson:                   2.386
Prob(Omnibus):                  0.014   Jarque-Bera (JB):                2.629
Skew:                           0.041   Prob(JB):                        0.269
Kurtosis:                       1.880   Cond. No.                     3.48e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.48e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
회귀 계수: 2.343
결정 계수: 0.37
0    106.38302
dtype: float64
<class 'pandas.core.series.Series'>
PIQ: 106