#### 유형1

In [39]:
import pandas as pd

df = pd.read_csv("student_assessment.csv")
# print(df.head())

# 1번 - 1
# df.info()
# print(df.isnull().sum())

# 결측 행 제거
df = df.dropna()
# print(df.isnull().sum())

# 학생이 가장 많이 수강한 과목
print(df['id_assessment'].value_counts())
max_id = df['id_assessment'].value_counts().idxmax()
print(max_id)

# print(df[df['id_assessment'] == 12]) #33개
result = (df['id_assessment'] == max_id)
df= df[result]

# 성적의 최고 점수
# print(df['score'].max())

# 수강생이 가장 많은 과목의 최고 점수
max_score = df[result]['score'].max()
print(max_score)

# 최고점수 표준화
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df['score'] = scaler.fit_transform(df[['score']])
print(round(df['score'].max(), 3))

id_assessment
12     33
47     32
8      31
113    29
39     28
       ..
77     11
18     10
43     10
83      9
71      9
Name: count, Length: 133, dtype: int64
12
99.0
2.183

C:\Users\LG\AppData\Local\Temp\ipykernel_9924\1344222174.py:27: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  max_score = df[result]['score'].max()

In [45]:
# 1번 - 2
import pandas as pd

df = pd.read_csv("stock_market.csv")
df.info()
print(df.head())

# close와 상관 계수 - 절대값
df_corr = df.corr()['close'].abs()
print(df_corr)

# 상관 관계가 높은 변수
col = df_corr.loc['DE1':'DE77'].idxmax()
print(col)

# 찾은 변수의 평균값
mean_val = df[col].mean()
print(round(mean_val, 4))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 80 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   DE1     1000 non-null   float64
 1   DE2     1000 non-null   float64
 2   DE3     1000 non-null   float64
 3   DE4     1000 non-null   float64
 4   DE5     1000 non-null   float64
 5   DE6     1000 non-null   float64
 6   DE7     1000 non-null   float64
 7   DE8     1000 non-null   float64
 8   DE9     1000 non-null   float64
 9   DE10    1000 non-null   float64
 10  DE11    1000 non-null   float64
 11  DE12    1000 non-null   float64
 12  DE13    1000 non-null   float64
 13  DE14    1000 non-null   float64
 14  DE15    1000 non-null   float64
 15  DE16    1000 non-null   float64
 16  DE17    1000 non-null   float64
 17  DE18    1000 non-null   float64
 18  DE19    1000 non-null   float64
 19  DE20    1000 non-null   float64
 20  DE21    1000 non-null   float64
 21  DE22    1000 non-null   float64
 22  DE23    1000 non-null   float64
 23  DE24    1000 non-null   float64
 24  DE25    1000 non-null   float64
 25  DE26    1000 non-null   float64
 26  DE27    1000 non-null   float64
 27  DE28    1000 non-null   float64
 28  DE29    1000 non-null   float64
 29  DE30    1000 non-null   float64
 30  DE31    1000 non-null   float64
 31  DE32    1000 non-null   float64
 32  DE33    1000 non-null   float64
 33  DE34    1000 non-null   float64
 34  DE35    1000 non-null   float64
 35  DE36    1000 non-null   float64
 36  DE37    1000 non-null   float64
 37  DE38    1000 non-null   float64
 38  DE39    1000 non-null   float64
 39  DE40    1000 non-null   float64
 40  DE41    1000 non-null   float64
 41  DE42    1000 non-null   float64
 42  DE43    1000 non-null   float64
 43  DE44    1000 non-null   float64
 44  DE45    1000 non-null   float64
 45  DE46    1000 non-null   float64
 46  DE47    1000 non-null   float64
 47  DE48    1000 non-null   float64
 48  DE49    1000 non-null   float64
 49  DE50    1000 non-null   float64
 50  DE51    1000 non-null   float64
 51  DE52    1000 non-null   float64
 52  DE53    1000 non-null   float64
 53  DE54    1000 non-null   float64
 54  DE55    1000 non-null   float64
 55  DE56    1000 non-null   float64
 56  DE57    1000 non-null   float64
 57  DE58    1000 non-null   float64
 58  DE59    1000 non-null   float64
 59  DE60    1000 non-null   float64
 60  DE61    1000 non-null   float64
 61  DE62    1000 non-null   float64
 62  DE63    1000 non-null   float64
 63  DE64    1000 non-null   float64
 64  DE65    1000 non-null   float64
 65  DE66    1000 non-null   float64
 66  DE67    1000 non-null   float64
 67  DE68    1000 non-null   float64
 68  DE69    1000 non-null   float64
 69  DE70    1000 non-null   float64
 70  DE71    1000 non-null   float64
 71  DE72    1000 non-null   float64
 72  DE73    1000 non-null   float64
 73  DE74    1000 non-null   float64
 74  DE75    1000 non-null   float64
 75  DE76    1000 non-null   float64
 76  DE77    1000 non-null   float64
 77  open    1000 non-null   float64
 78  close   1000 non-null   float64
 79  volume  1000 non-null   float64
dtypes: float64(80)
memory usage: 625.1 KB
        DE1       DE2       DE3       DE4       DE5       DE6       DE7  \
0  1.764052  0.400157  0.978738  2.240893  1.867558 -0.977278  0.950088
1 -0.578850 -0.311553  0.056165 -1.165150  0.900826  0.465662 -1.536244
2 -0.098453 -0.663478  1.126636 -1.079932 -1.147469 -0.437820 -0.498032
3 -0.493320 -0.542861  0.416050 -1.156182  0.781198  1.494485 -2.069985
4  0.693773 -0.159573 -0.133702  1.077744 -1.126826 -0.730678 -0.384880

        DE8       DE9      DE10  ...      DE71      DE72      DE73      DE74  \
0 -0.151357 -0.103219  0.410599  ...  0.729091  0.128983  1.139401 -1.234826
1  1.488252  1.895889  1.178780  ...  1.117016 -1.315907 -0.461585 -0.068242
2  1.929532  0.949421  0.087551  ... -1.540797  0.063262  0.156507  0.232181
3  0.426259  0.676908 -0.637437  ...  1.658131 -0.118164 -0.680178  0.666383
4  0.094352 -0.042171 -0.286887  ... -0.206904  0.880179 -1.698106  0.387280

       DE75      DE76      DE77        open       close    volume
0  0.402342 -0.684810 -0.870797  129.549102  126.502056  981466.0
1  1.713343 -0.744755 -0.826439  126.502056  128.041811  473416.0
2 -0.597316 -0.237922 -1.424061  128.041811  128.957651   46597.0
3 -0.460720 -1.334258 -1.346718  128.957651  122.965246  455747.0
4 -2.255564 -1.022507  0.038631  122.965246  114.922790  242198.0

[5 rows x 80 columns]
DE1       0.034633
DE2       0.052457
DE3       0.021811
DE4       0.025823
DE5       0.001282
            ...
DE76      0.012707
DE77      0.020981
open      0.996873
close     1.000000
volume    0.022469
Name: close, Length: 80, dtype: float64
DE14
-0.0004

In [49]:
# 1번 - 3
import pandas as pd

df = pd.read_csv("air_quality.csv")
print(df)

# IQR 계산
Q1 = df['CO2'].quantile(0.25)
Q3 = df['CO2'].quantile(0.75)
IQR = Q3 - Q1
print(IQR)

# 상한 및 하한 계산
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

# 이상치 식별
result = (df['CO2'] < lower) | (df['CO2'] > upper)
print(df[result])
outliers = df[result]
print(len(outliers))

                     Date        CO         CO2         O2
0     2024-01-01 00:00:00  0.549671  383.037632  21.248286
1     2024-01-01 01:00:00  0.486174  392.362513  21.183324
2     2024-01-01 02:00:00  0.564769  385.065473  19.963480
3     2024-01-01 03:00:00  0.652303  402.760451  21.479584
4     2024-01-01 04:00:00  0.476585  429.929463  19.409917
...                   ...       ...         ...        ...
9995  2025-02-20 11:00:00  0.630110  409.695684  20.322712
9996  2025-02-20 12:00:00  0.300166  434.434164  22.344604
9997  2025-02-20 13:00:00  0.429468  409.458849  20.398633
9998  2025-02-20 14:00:00  0.549577  442.838243  19.007643
9999  2025-02-20 15:00:00  0.564439  359.502005  20.671116

[10000 rows x 4 columns]
34.92822611304376
                     Date        CO         CO2         O2
88    2024-01-04 16:00:00  0.447024  603.471090  20.712496
155   2024-01-07 11:00:00  0.428565  588.211313  22.013521
185   2024-01-08 17:00:00  0.571400  472.852730  21.667225
196   2024-01-09 04:00:00  0.411614  607.631613  21.072704
228   2024-01-10 12:00:00  0.428470  595.429242  20.319365
...                   ...       ...         ...        ...
9908  2025-02-16 20:00:00  0.606182  595.889840  21.572550
9938  2025-02-18 02:00:00  0.373704  627.451289  20.840325
9953  2025-02-18 17:00:00  0.403922  639.521653  19.060725
9962  2025-02-19 02:00:00  0.568850  328.099193  21.601589
9966  2025-02-19 06:00:00  0.451337  646.129551  20.328131

[304 rows x 4 columns]
304

### 2유형

In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
import numpy as np

train = pd.read_csv("mart_train.csv")
test = pd.read_csv("mart_test.csv")

train.info()
# train.head()
# print(train.shape, test.shape)

# 원-핫 인코딩
train = pd.get_dummies(train)
test = pd.get_dummies(test)

# 데이터 선택
X = train.drop("total", axis=1)
y = train["total"]
# target = train.pop("total")
print(train.shape, test.shape)

train.info()

# 학습용 데이터 분할
# X_train, X_test, y_train, y_test = train_test_split(train,
#         target, test_size=0.2, random_state=303)

# print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)

# # 머신러닝 모델 생성 및 학습
# model = RandomForestRegressor(random_state=303)
# model.fit(X_train, y_train)
# pred = model.predict(X_test)
# # pred

# # 성능 평가 - 지표 : RMSE(평균 제곱근 오차)
# def rmse(y_true, y_pred):
#     return mean_squared_error(y_true, y_pred) ** 0.5

# # rmse = rmse(y_test, pred)

# # numpy 사용
# mse = mean_squared_error(y_test, pred)
# print("MSE:", mse)

# rmse = np.sqrt(mse)
# print("RMSE:", rmse)

# # 평가용 데이터 예측 및 결과 파일
# pred2 = model.predict(test)
# print(pred2)

# result_df = pd.DataFrame({"pred": pred2})
# result_df.to_csv("result.csv", index=False)

# pd.read_csv("result.csv")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   branch          700 non-null    object
 1   city            700 non-null    object
 2   customer_type   700 non-null    object
 3   gender          700 non-null    object
 4   product_line    700 non-null    object
 5   total           700 non-null    float64
 6   payment_method  700 non-null    object
 7   rating          700 non-null    float64
 8   time_of_day     700 non-null    object
 9   day_name        700 non-null    object
dtypes: float64(2), object(8)
memory usage: 54.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 30 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   rating                               700 non-null    float64
 1   branch_A                             700 non-null    bool
 2   branch_B                             700 non-null    bool
 3   branch_C                             700 non-null    bool
 4   city_Mandalay                        700 non-null    bool
 5   city_Naypyitaw                       700 non-null    bool
 6   city_Yangon                          700 non-null    bool
 7   customer_type_Member                 700 non-null    bool
 8   customer_type_Normal                 700 non-null    bool
 9   gender_Female                        700 non-null    bool
 10  gender_Male                          700 non-null    bool
 11  product_line_Electronic accessories  700 non-null    bool
 12  product_line_Fashion accessories     700 non-null    bool
 13  product_line_Food and beverages      700 non-null    bool
 14  product_line_Health and beauty       700 non-null    bool
 15  product_line_Home and lifestyle      700 non-null    bool
 16  product_line_Sports and travel       700 non-null    bool
 17  payment_method_Cash                  700 non-null    bool
 18  payment_method_Credit card           700 non-null    bool
 19  payment_method_Ewallet               700 non-null    bool
 20  time_of_day_afternoon                700 non-null    bool
 21  time_of_day_evening                  700 non-null    bool
 22  time_of_day_morning                  700 non-null    bool
 23  day_name_Friday                      700 non-null    bool
 24  day_name_Monday                      700 non-null    bool
 25  day_name_Saturday                    700 non-null    bool
 26  day_name_Sunday                      700 non-null    bool
 27  day_name_Thursday                    700 non-null    bool
 28  day_name_Tuesday                     700 non-null    bool
 29  day_name_Wednesday                   700 non-null    bool
dtypes: bool(29), float64(1)
memory usage: 25.4 KB
(560, 30) (560,) (140, 30) (140,)
MSE: 141081753599.14426
RMSE: 375608.511084539
[301405.23   612985.59   420745.9725 616315.77   470881.0575 456151.185
 508195.6425 530082.945  478857.8025 485198.1225 471013.9875 373547.6325
 556442.145  441640.71   389083.59   522364.6575 453153.96   544868.2575
 610219.575  547865.955  316139.355  680789.34   295322.265  719249.265
 489927.8475 496896.5925 366496.83   524635.65   357611.4675 488458.0575
 534492.63   564329.5875 633973.8825 366390.99   358501.6575 416016.5625
 510554.52   531820.6425 538253.5725 442765.89   585549.8775 531360.585
 680841.4725 419025.1275 845108.775  695634.5025 418739.1075 608342.9625
 466887.645  767059.8075 540218.385  453593.07   465392.655  381697.9425
 880095.825  617843.3625 529862.76   562281.93   430793.2125 479337.705
 563380.02   492103.8675 467250.0525 673481.1825 553334.355  515845.7325
 454537.9125 423042.165  456237.18   587721.1725 387879.975  421599.9375
 436381.6275 634133.5875 470193.57   474434.1    634511.115  472915.8
 480256.875  466179.6825 438183.9    366840.495  550920.0375 687297.555
 704351.97   350483.175  462452.13   414589.14   436975.56   419939.2575
 524209.455  661777.2    445385.43   435600.1125 675701.46   598199.49
 574181.8425 441473.6025 358434.405  453040.56   323910.8775 662630.0625
 395946.6525 469963.4625 521060.2425 495166.77   540648.8325 592914.105
 752352.7725 432982.4625 388379.88   564568.6725 896889.735  409817.3625
 377492.0625 504970.515  632489.2875 442842.12   550367.685  487899.72
 220494.96   745499.16   460180.8225 612632.79   628190.01   533246.9625
 553991.13   696371.445  530658.6075 561689.73   869802.0975 485075.745
 618204.195  553270.8825 461958.84   527007.1275 293600.475  484114.05
 437886.0675 536622.03   518793.5025 757396.395  490696.92   731410.6275
 474615.855  382142.4075 415750.0725 491103.27   524700.225  437013.99
 688141.9125 503808.165  480097.485  638479.9575 573116.67   700052.3775
 388168.6725 427285.0575 592512.6375 383839.9425 441691.11   459514.755
 571920.4575 427593.7575 519996.4875 647065.9125 550874.835  655941.6675
 772347.555  534664.305  434214.4275 415992.3075 544924.0125 442561.455
 384169.7475 366122.7675 308861.4375 424329.255  640742.76   525193.83
 536271.2775 481043.2725 557882.325  736865.4825 609597.2925 427536.1125
 293149.08   571596.0075 298860.1875 352766.4525 449784.2475 470679.7725
 427079.52   499735.6875 542920.9275 532287.     569590.56   798332.6925
 471411.8325 651187.0575 492325.3125 442973.16   544988.9025 469001.1375
 420046.0425 630471.0825 407122.8525 531667.8675 519628.725  534015.5625
 504502.5825 536092.83   360606.33   696554.145  416321.64   247280.04
 469551.915  308770.4025 352847.25   694218.2625 634984.875  459544.8375
 771970.3425 448818.4575 384731.7075 406407.33   539440.02   409911.2325
 547169.175  478849.14   356835.9375 481043.2725 470024.2575 517813.8525
 393216.2325 475971.1425 622382.5125 554394.015  627256.665  417055.1175
 376053.7725 464815.575  401203.3725 479275.335  574039.62   626849.37
 591973.515  381559.0275 490374.675  576513.945  447085.0125 509098.59
 594185.2875 664425.72   324181.62   428286.7575 459904.2525 468882.855
 566286.84   547309.5075 579729.465  640996.1775 737425.5525 503900.3025
 594476.9775 764275.8375 594055.35   543621.1725 476997.255  326512.7775
 477526.6125 280787.0625 469571.2875 532613.4975 472022.9325 463648.9725
 467211.465  433057.4325 604297.4175 520874.7075 752960.0925 594838.2825
 527236.1325 505300.1625 539668.5525 364050.3825 515534.5125 612889.0425
 807245.6175 618700.32   609463.1025 428307.39   409731.0525 209156.22
 477712.4625 395597.79   591013.5525 471036.195  316240.155  461092.59  ]

            pred
0    301405.2300
1    612985.5900
2    420745.9725
3    616315.7700
4    470881.0575
..           ...
295  395597.7900
296  591013.5525
297  471036.1950
298  316240.1550
299  461092.5900

[300 rows x 1 columns]

#### 3유형

In [63]:
# 1 - 1번
import pandas as pd
from statsmodels.formula.api import logit
import numpy as np

df = pd.read_csv("clam.csv")
# df.info()
# df.head()

# 데이터셋 분할
train = df.iloc[:210]
test = df.iloc[210:]
print(train.shape, test.shape)

# 로지스틱 회귀 모델 생성 및 훈련 데이터로 학습
model = logit("gender ~ weight", train).fit()
print(model.summary())

print(model.params)
print(model.pvalues)
w_coef = model.params['weight']
# print(w_coef)

# 오즈비 계산
odds_ratio = np.exp(w_coef)
print(round(odds_ratio, 4))

# 1 - 2번

# 모델 학습
formula = "gender ~ age + length + diameter + height + weight"
model2 = logit(formula, train).fit()

# 잔치 이탈도
result = -2 * model2.llf
print(round(result, 2))

from sklearn.metrics import accuracy_score
# 1 -3번
# 1) test데이터를 사용해 예측 (0.5 미만: 0, 0.5 이상 1)
model = logit("gender ~ weight", data=train).fit()
target = test.pop('gender')
pred = model.predict(test)
# pred = (pred > 0.5).astype(int)
pred = pred.astype(int)

# 2) 실제 값과 예측값을 사용하여 정확도 계산
accuracy = accuracy_score(target, pred)
print(accuracy)

# 3) 오류율 계산
error_rate = 1 - accuracy
print(round(error_rate, 3))

(210, 6) (90, 6)
Optimization terminated successfully.
         Current function value: 0.690045
         Iterations 4
                           Logit Regression Results
==============================================================================
Dep. Variable:                 gender   No. Observations:                  210
Model:                          Logit   Df Residuals:                      208
Method:                           MLE   Df Model:                            1
Date:                Fri, 24 Jan 2025   Pseudo R-squ.:                0.003431
Time:                        18:57:37   Log-Likelihood:                -144.91
converged:                       True   LL-Null:                       -145.41
Covariance Type:            nonrobust   LLR p-value:                    0.3178
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -0.3140      0.276     -1.137      0.256      -0.855       0.227
weight         0.0047      0.005      0.997      0.319      -0.005       0.014
==============================================================================
Intercept   -0.313969
weight       0.004706
dtype: float64
Intercept    0.255506
weight       0.318876
dtype: float64
1.0047
Optimization terminated successfully.
         Current function value: 0.683173
         Iterations 4
286.93
Optimization terminated successfully.
         Current function value: 0.690045
         Iterations 4
0.5222222222222223
0.478

In [162]:
# 3 - 2번
import pandas as pd
from statsmodels.formula.api import ols

df = pd.read_csv("system_cpu.csv")
# df.info()
# df.head()

# ERP와 상관 관계가 높은 값
corr = df.corr()
max_val = corr['ERP'].max()
print(round(max_val, 3))

# CPU가 100미만인 데이터로 선형 회귀 모델 구축
cond = df['CPU'] < 100
new_df = df[cond]

formula = "ERP ~ Feature1 + Feature2 + Feature3 + CPU"
model = ols(formula, new_df).fit()
print(model.summary())

# 결정 계수
print("R2:", round(model.rsquared, 3))

# p-value가 가장 높은 값
max_val = model.pvalues.max()
print(round(max_val, 3))

1.0
                            OLS Regression Results
==============================================================================
Dep. Variable:                    ERP   R-squared:                       0.755
Model:                            OLS   Adj. R-squared:                  0.736
Method:                 Least Squares   F-statistic:                     39.30
Date:                Tue, 26 Nov 2024   Prob (F-statistic):           5.36e-15
Time:                        08:33:53   Log-Likelihood:                -260.40
No. Observations:                  56   AIC:                             530.8
Df Residuals:                      51   BIC:                             540.9
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     51.4133     19.112      2.690      0.010      13.045      89.782
Feature1      -0.0242      0.059     -0.409      0.684      -0.143       0.094
Feature2       0.0602      0.106      0.569      0.572      -0.152       0.273
Feature3       1.4126      0.113     12.458      0.000       1.185       1.640
CPU           -0.4651      0.234     -1.985      0.053      -0.936       0.005
==============================================================================
Omnibus:                        3.758   Durbin-Watson:                   1.762
Prob(Omnibus):                  0.153   Jarque-Bera (JB):                2.757
Skew:                           0.436   Prob(JB):                        0.252
Kurtosis:                       3.648   Cond. No.                         780.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
R2: 0.755
0.684